services:

  app:
    container_name: postvel_app
    image: postvel_app
    restart: unless-stopped
    ports:
      - "8081:80"
    working_dir: /var/www/
    volumes:
      - ./../app:/var/www
      - ./../dkim:/etc/dkim
    depends_on:
      mysql:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - API_TOKEN
    networks:
      - postvel

  postfix:
    container_name: postvel_postfix
    image: postvel_postfix
    restart: unless-stopped
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.app
    depends_on:
      - fluentd
    networks:
      - postvel

  fluentd:
    image: fluent/fluentd:v1.17.1-1.0
    container_name: postvel_fluentd
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "127.0.0.1:24224:24224"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - API_TOKEN
    networks:
      - postvel

  mysql:
    image: mysql:9.1.0
    container_name: postvel_mysql
    restart: unless-stopped
    ports:
      - "23306:3306"
    environment:
      MYSQL_DATABASE: postvel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: postvel
    command: --skip-log-bin
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=secret --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 60s
      retries: 30
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - postvel

  redis:
    image: redis:7.4.1
    container_name: postvel_redis
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - postvel

networks:
  postvel:
    driver: bridge
